// Patches relationship files for PowerPoint parts (presentation, slides,
// slide layouts, slide masters, notes, themes, etc.). Handles any .rels file
// under ppt/ — e.g. ppt/_rels/presentation.xml.rels,
// ppt/slides/_rels/slide1.xml.rels, ppt/slideMasters/_rels/slideMaster1.xml.rels.
//
// These .rels files contain non-deterministic relationship IDs generated by
// OpenXml SDK methods such as AddPart. This patcher renumbers them to
// deterministic "DeterministicId{n}" values and stores the old→new mapping
// so the corresponding content patcher (PptxContentPatcher) can remap r:id
// references in the matching XML content file.
class PptxRelationshipPatcher : IPatcher
{
    // Keyed by content file name (e.g. "ppt/slides/slide1.xml") → old-to-new ID mapping
    internal Dictionary<string, Dictionary<string, string>> IdMappings { get; } = new(StringComparer.OrdinalIgnoreCase);

    public bool IsMatch(Entry entry) =>
        entry.FullName.StartsWith("ppt/") &&
        entry.FullName.Contains("/_rels/") &&
        entry.FullName.EndsWith(".xml.rels");

    public void PatchXml(XDocument xml, string entryName)
    {
        var mapping = RelationshipRenumber.RenumberAndSort(xml, entryName);

        // Derive content file path from .rels path:
        // "ppt/slides/_rels/slide1.xml.rels" → "ppt/slides/slide1.xml"
        // "ppt/_rels/presentation.xml.rels" → "ppt/presentation.xml"
        var contentName = entryName
            .Replace("/_rels/", "/")
            .Replace(".xml.rels", ".xml");
        IdMappings[contentName] = mapping;
    }
}
