// Patches relationship files for Word sub-parts (headers, footers, etc.).
// Handles word/_rels/footer1.xml.rels, word/_rels/header1.xml.rels, etc.
// Excludes word/_rels/document.xml.rels which has its own dedicated patcher.
//
// These .rels files contain non-deterministic relationship IDs generated by
// AddHyperlinkRelationship and similar OpenXml SDK methods. This patcher
// renumbers them to deterministic "DeterministicId{n}" values and stores
// the old→new mapping so the corresponding content patcher (WordPartPatcher)
// can remap r:id references in the XML content.
class WordPartRelationshipPatcher : IPatcher
{
    // Keyed by content file name (e.g. "word/footer1.xml") → old-to-new ID mapping
    internal Dictionary<string, Dictionary<string, string>> IdMappings { get; } = new(StringComparer.OrdinalIgnoreCase);

    public bool IsMatch(Entry entry) =>
        entry.FullName.StartsWith("word/_rels/") &&
        entry.FullName != "word/_rels/document.xml.rels" &&
        entry.FullName.EndsWith(".xml.rels");

    public void PatchXml(XDocument xml, string entryName)
    {
        var mapping = RelationshipRenumber.RenumberAndSort(xml, entryName);

        // Derive content file path from .rels path:
        // "word/_rels/footer1.xml.rels" → "word/footer1.xml"
        var contentName = entryName
            .Replace("/_rels/", "/")
            .Replace(".xml.rels", ".xml");
        IdMappings[contentName] = mapping;
    }
}
